// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmWSJB7JXTv0iz-Dk2NiF8WxXs0gdCNHo',
    appId: '1:311505560380:web:672ba91cf02f92907fb439',
    messagingSenderId: '311505560380',
    projectId: 'kita-5a01e',
    authDomain: 'kita-5a01e.firebaseapp.com',
    storageBucket: 'kita-5a01e.firebasestorage.app',
    measurementId: 'G-1SW0RHP1CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsJYHZ0fZDynIpOCNED9aGOxVvTlGhTpg',
    appId: '1:311505560380:android:7fad08350274b8677fb439',
    messagingSenderId: '311505560380',
    projectId: 'kita-5a01e',
    storageBucket: 'kita-5a01e.firebasestorage.app',
  );
}
